spring.application.name=ProjectManagementSystem

server.port=8081

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/project_management_db
spring.datasource.username=postgres
spring.datasource.password=ines
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Entity packages to scan
spring.jpa.properties.hibernate.packagesToScan=com.ProjectManagementSystem.modal
spring.jpa.properties.packagesToScan=com.ProjectManagementSystem.modal